name: Build and Deploy HTML to EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build project
        run: |
          echo "Building project..."
          mkdir -p build
          cp -r ./* build/     # Copy all repo files into build folder
          ls -l build/          # Optional: verify contents

     
      - name: Deploy to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ SSH_HOST }}
          username: ${{ SSH_USERNAME }}
          key: ${{ SSH_PRIVATE_KEY }}
          port: 22
          source: "./build/*"        
          target: "/var/www/html"
          rm: true                   

     
      - name: Configure Apache and fix permissions
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ SSH_HOST }}
          username: ${{ SSH_USERNAME }}
          key: ${{ SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Change ownership so Apache can serve files
            sudo chown -R www-data:www-data /var/www/html
            
            # Set directory permissions
            sudo find /var/www/html -type d -exec chmod 755 {} \;
            
            # Set file permissions
            sudo find /var/www/html -type f -exec chmod 644 {} \;
            
            # Restart Apache to apply changes
            sudo systemctl restart apache2
